### ISSUE TITLE
ActionMenu with overflow doesn’t contain scrollbars within its rounded border

### ISSUE THREAD

**Issue by dylanatsmith** [primer/react#4938]
### Description

Scrollbar contained within rounded corners of ActionList

![image](https://github.com/user-attachments/assets/354bc902-dc03-4731-95ba-7ba456670f36)

### Steps to reproduce

1. Put a whole bunch of items in an ActionMenu too short to contain them
2. You may need to force enable scrollbars at OS level

### Version

Whatever’s in dotcom

**Comment by siddharthkp** [comment]
Passerby notes: `overflow: scroll` should be on the ActionList inside the Overlay. not on the overflow itself, that way we can ensure the border radius of the Overlay stays intact

**Comment by lesliecdubs** [comment]
Wondering if someone in Primer Design might be able to take a look and weigh in on the CSS change needed here?

**Comment by tallys** [comment]
@camertron can you follow up on this if it's React?

**Comment by lesliecdubs** [comment]
@tallys confirmed via Storybook that this appears to be happening in React.

**Comment by francinelucca** [comment]
Tested this suggestion: https://github.com/primer/react/issues/4938#issuecomment-2340216670. Setting the overflow inside the ActionList doesn't solve the problem by itself because the ActionList is unaware of the max-height set by the overlay due to the overlay being absolutely positioned. In order for the overflow to work in the ActionList, it would have to be given a max-height as well. Throwing this back in the backlog as a solution for this will require further discussion

**Comment by sunnyi101** [comment]
Thanks for submitting this issue! We’ll review it during monthly planning preparation to consider picking up based on current priorities.

**Comment by francisfuzz** [comment]
> Throwing this back in the backlog as a solution for this will require further discussion

@francinelucca - Hi! I was looking at your issue comment in https://github.com/primer/react/issues/4938#issuecomment-2492089164 and came across this last line as a part of our internal work efforts. I am wondering where the discussion for the solution would normally happen: in this issue, in `github`'s Slack channels, or elsewhere?

**Comment by francinelucca** [comment]
@francisfuzz  Usually in our internal triage meetings that happen on Mondays. That's where @sunnyi101's comment above came from. Next steps here would be to scope this work as part of a work stream which @sunnyi101/ @hellojanehere might have more context on. I see it has been included in the Paper Cuts board so there's a chance it gets worked on this week 🤞

**Comment by pksjce** [comment]
Picked this up as my next papercut

I tested this story https://primer.style/react/storybook/?path=/story/components-actionmenu-examples--setting-max-height
And found that the scroll is not working at all. As in there are are a 100 items on that menu but I can see only 13. I can scroll with the down arrow on the keyboard but the vertical scrollbar and mouse scroll don't seem to work

Solution- It looks like `Overlay` component has styles for `data-overflow` attribute but doesn't actually set that attribute. Will throw up a PR to fix this.
Once this fix is in, we can decide if the scrollbar looks right to mark this issue as resolved.\

**Comment by pksjce** [comment]
I have merged my fix. IMO we can close this bug. Waiting for confirmation by OP on this.

**Comment by crittermike** [comment]
Any info about when this fix will make it to dotcom? We're still seeing the issue on the security configurations page.

**Comment by francinelucca** [comment]
This fix was released as part of 37.28.0, which should already be in dotcom. Can you provide repro instructions for security configurations @crittermike ? we might need to reopen this bug

**Comment by crittermike** [comment]
Is there any way to see Storybook for that version? I'm looking at https://primer.style/react/storybook/?path=/story/components-actionmenu-examples--setting-max-height which is still broken but that's still 37.27.0. 

I can provide repro instructions but I'd need to add folks to an org that has a ton of security configurations to test - are you the right person to add?

**Comment by francinelucca** [comment]
Tested in the [deployment for v37.28.0](https://primer-b6359a5ebe-13348165.drafts.github.io/storybook/?path=/story/components-actionmenu-examples--setting-max-height) can confirm scroll is now present but the border radius still does not look correct, reopening issue

**Comment by pksjce** [comment]
Hey @francinelucca ! can you put in a screenshot/clip of what you are seeing in this deployment?
Is this the buggy behaviour?

<img width="200" height="408" alt="Image" src="https://github.com/user-attachments/assets/d04e3c05-74ca-4047-aff1-9df6ef454007" />

**Comment by francinelucca** [comment]
<img width="518" height="524" alt="Image" src="https://github.com/user-attachments/assets/477d8227-7ec3-4857-9aed-35bfc66fb5a5" />
@pksjce need to set scrollbars to always 

<img width="481" height="576" alt="Image" src="https://github.com/user-attachments/assets/a11ae9ae-5ed0-4445-9592-0338b4adb856" />

**Comment by hellojanehere** [comment]
@pksjce moved this back to in progress :)

**Comment by pksjce** [comment]
@crittermike - Do you have any example of what this should look like in the fixed case scenario?
Or is this an issue with scrollbars with all primer components?
Thanks for your patience with this!

**Comment by francinelucca** [comment]
I believe it should look like this (overflow inside ActionList, not Overlay)

<img width="423" height="481" alt="Image" src="https://github.com/user-attachments/assets/409d9d1c-1f25-4191-824b-cd3066606e3f" />

**Comment by pksjce** [comment]
This can now be marked as fixed. Here's what the change looks like. Its a tiny improvement to the scrollbar with border radius.

**Before**

https://github.com/user-attachments/assets/3d57b929-6554-4698-a130-e387a79b48d0

**After**

https://github.com/user-attachments/assets/e6535de7-2193-4199-943c-4ff2b288f9c1
